name: b_be_bee_app
description: An open source cross-platform music client ,compatible across multiple platforms utilizing BiliBili's data API and Spotify and YouTube as an audio source
homepage: https://b_be_bee.com/
publish_to: "none"

version: 0.1.1

environment:
  flutter: ">=3.24.0"
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  connectivity_plus: ^6.1.0
  device_info_plus: ^11.1.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path: ^1.9.0
  tray_manager: ^0.2.4
  window_manager: ^0.4.3
  windows_taskbar: ^1.1.2
  flex_color_scheme: ^8.0.2
  palette_generator: ^0.3.3+6
  vibration: ^3.1.3
  text_scroll: ^0.2.0
  fftea: ^1.5.0+1

  #路由
  routerino: ^0.8.0

  # 存储
  hive_ce: ^2.9.0
  hive_ce_flutter: ^2.1.0
  cached_network_image: ^3.4.1

  # 功能
  pretty_qr_code: ^3.3.0 # 生成二维码
  gt3_flutter_plugin: ^0.1.1 # 登录人机校验
  shimmer: ^3.0.0 # 加载网络图片提高用户体验
  easy_refresh: ^3.4.0 # 下拉
  toastification : ^2.3.0 # toast
  flutter_inappwebview : ^6.1.5 # webview
  url_launcher: ^6.3.1 # scheme
  slang: ^4.4.0 # i18n
  slang_flutter: ^4.4.0
  flutter_displaymode: ^0.6.0 # 安卓高刷
  uuid: ^4.5.1 # uuid
  encrypt: ^5.0.3
  flutter_markdown: ^0.7.4+2
  appscheme: ^1.1.0
  wakelock_plus: ^1.1.4
  permission_handler: ^11.3.1
  html: ^0.15.5
  share_plus: ^10.1.4
  image_gallery_saver: ^2.0.3
  mobile_scanner: ^6.0.6
  google_mlkit_barcode_scanning: ^0.13.0
  image_picker: ^1.1.2
  shared_storage: ^0.8.1
  file_picker: ^9.0.1
  flutter_screenutil: 5.9.3
  open_filex: ^4.7.0 #安装更新

  # 网络
  rhttp: ^0.11.0
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  webview_cookie_manager: ^2.0.6

  # 日志
  logging: ^1.3.0

  # 自动生成文件
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^2.4.4

  # 状态管理
  flutter_riverpod: ^2.6.1

  # 播放器
  just_audio:
    git:
#      url: https://github.com/ryanheise/just_audio.git
      url: https://github.com/BBeBeeX/just_audio.git
      ref: visualizer
      path: just_audio
  just_audio_media_kit:
    git:
      url: https://github.com/BBeBeeX/just_audio_media_kit.git
      ref: main

  audio_service: ^0.18.17
  media_kit_libs_linux: 1.1.3
  media_kit_libs_windows_audio: 1.0.9
#  media_kit_libs_android_audio: 1.3.5
#  media_kit_libs_ios_audio: 1.1.4
#  media_kit_libs_macos_audio: 1.1.4
#  ffmpeg_kit_flutter: ^6.0.3 # 文件格式转换
  ffmpeg_helper:
    git:
      url: https://github.com/BBeBeeX/ffmpeg_helper.git
      ref: 61986a490e9fc73b27bcac83fe6dbc87c7db1792


# windows
  bitsdojo_window: ^0.1.6

dev_dependencies:
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  slang_build_runner: ^4.4.0
  test: ^1.24.8
  hive_ce_generator: ^1.8.1

dependency_overrides:
  pasteboard:
    git:
      url: https://github.com/Seidko/flutter-plugins.git
      ref: 58748dae405df5e68a131e4905d48e75d0624be2
      path: packages/pasteboard
  permission_handler_windows:
    git:
      url: https://github.com/localsend/permission_handler_windows_noop.git
      ref: 2dadd8afbf81e0e3e4791d7144e689555e58f649
  just_audio_platform_interface:
    git:
      url: https://github.com/ryanheise/just_audio.git
      ref: visualizer
      path: just_audio_platform_interface


flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/web/
    - assets/CHANGELOG.md
    - assets/icons/

flutter_gen:
  line_length: 150
