import '../gen/strings.g.dart';

class BiliErrorMessage {
  static String getErrorMessage(int? code) {
    switch (code) {
      case 0:
        return t.common.biliError.case0;
      case -1:
        return t.common.biliError.case_1;
      case -2:
        return t.common.biliError.case_2;
      case -3:
        return t.common.biliError.case_3;
      case -4:
        return t.common.biliError.case_4;
      case -101:
        return t.common.biliError.case_101;
      case -102:
        return t.common.biliError.case_102;
      case -103:
        return t.common.biliError.case_103;
      case -104:
        return t.common.biliError.case_104;
      case -105:
        return t.common.biliError.case_105;
      case -106:
        return t.common.biliError.case_106;
      case -107:
        return t.common.biliError.case_107;
      case -108:
        return t.common.biliError.case_108;
      case -110:
        return t.common.biliError.case_110;
      case -111:
        return t.common.biliError.case_111;
      case -112:
        return t.common.biliError.case_112;
      case -113:
        return t.common.biliError.case_113;
      case -114:
        return t.common.biliError.case_114;
      case -115:
        return t.common.biliError.case_115;
      case -304:
        return t.common.biliError.case_304;
      case -307:
        return t.common.biliError.case_307;
      case -352:
        return t.common.biliError.case_352;
      case -400:
        return t.common.biliError.case_400;
      case -401:
        return t.common.biliError.case_401;
      case -403:
        return t.common.biliError.case_403;
      case -404:
        return t.common.biliError.case_404;
      case -405:
        return t.common.biliError.case_405;
      case -409:
        return t.common.biliError.case_409;
      case -412:
        return t.common.biliError.case_412;
      case -500:
        return t.common.biliError.case_500;
      case -503:
        return t.common.biliError.case_503;
      case -504:
        return t.common.biliError.case_504;
      case -509:
        return t.common.biliError.case_509;
      case -616:
        return t.common.biliError.case_616;
      case -617:
        return t.common.biliError.case_617;
      case -625:
        return t.common.biliError.case_625;
      case -626:
        return t.common.biliError.case_626;
      case -628:
        return t.common.biliError.case_628;
      case -629:
        return t.common.biliError.case_629;
      case -632:
        return t.common.biliError.case_632;
      case -643:
        return t.common.biliError.case_643;
      case -650:
        return t.common.biliError.case_650;
      case -652:
        return t.common.biliError.case_652;
      case -653:
        return t.common.biliError.case_653;
      case -658:
        return t.common.biliError.case_658;
      case -662:
        return t.common.biliError.case_662;
      case -688:
        return t.common.biliError.case_688;
      case -689:
        return t.common.biliError.case_689;
      case -701:
        return t.common.biliError.case_701;
      case -799:
        return t.common.biliError.case_799;
      case -2001:
        return t.common.biliError.case_2001;
      case -2100:
        return t.common.biliError.case_2100;
      case -8888:
        return t.common.biliError.case_8888;
      case 1002:
        return t.common.biliError.case1002;
      case 1003:
        return t.common.biliError.case1003;
      case 1025:
        return t.common.biliError.case1025;
      case 2400:
        return t.common.biliError.case2400;
      case 2406:
        return t.common.biliError.case2406;
      case 86000:
        return t.common.biliError.case86000;
      case 86101:
        return t.common.biliError.case86101;
      case 86090:
        return t.common.biliError.case86090;
      case 86038:
        return t.common.biliError.case86038;
      case 86103:
        return t.common.biliError.case86103;
      case 86203:
        return t.common.biliError.case86203;
      default:
        return t.common.biliError.kDefault(code: code.toString());
    }
  }
}


