const List<Map<String, String>> allRecommends = [
  {'id': '1367065', 'type': 'bili_season', 'title': '推荐歌单 合集·澤野弘之'},
  {'id': '572226', 'type': 'bili_season', 'title': '推荐歌单 合集·4K日漫音乐现场'},
  {'id': '1321275', 'type': 'bili_season', 'title': '推荐歌单 合集·4K日语音乐现场'},
  {'id': '1983842', 'type': 'bili_season', 'title': '推荐歌单 合集·4K欧美音乐现场'},
  {'id': '4236201', 'type': 'bili_season', 'title': '推荐歌单 合集·4K粤语音乐现场'},
  {'id': '1321294', 'type': 'bili_season', 'title': '推荐歌单 合集·4K纯音乐/器乐现场'},
  {'id': '1939498', 'type': 'bili_season', 'title': '推荐歌单 4K日语神级现场'},
  {'id': '1082061', 'type': 'bili_season', 'title': '推荐歌单 音乐现场'},
  {'id': '1541968', 'type': 'bili_season', 'title': '推荐歌单 经典动漫神曲'},
  {'id': '3456912', 'type': 'bili_season', 'title': '推荐歌单 合集·日韩破亿神曲'},
  {'id': '257515', 'type': 'bili_season', 'title': '推荐歌单 合集·欧美粉必听,收藏过百万热歌全集'},
  {'id': '1250489', 'type': 'bili_season', 'title': '推荐歌单 合集·周杰伦—永远的青春'},
  {'id': '1383216', 'type': 'bili_season', 'title': '推荐歌单 合集·这是多少人的青春啊'},
  {'id': '2933823', 'type': 'bili_season', 'title': '推荐歌单 合集·一人一首代表作！持续更新！'},
  {'id': '693345', 'type': 'bili_season', 'title': '推荐歌单 合集·听！动漫的名场面'},
  {'id': '2671401', 'type': 'bili_season', 'title': '推荐歌单 合集·霉霉神现场合集'},
  {'id': '3755783', 'type': 'bili_season', 'title': '推荐歌单 合集·全是洗脑神曲啊'},
  {'id': '3502852', 'type': 'bili_season', 'title': '推荐歌单 合集·奥运会歌曲'},
  {'id': '328371', 'type': 'bili_season', 'title': '推荐歌单 合集·今晚村口集合！劲舞团还是QQ飞车随你挑'},
  {'id': '874587', 'type': 'bili_season', 'title': '推荐歌单 合集·世界杯名曲合集'},
  {'id': '1598546', 'type': 'bili_season', 'title': '推荐歌单 合集·身临其境！一起来大合唱吧'},
  {'id': '230679', 'type': 'bili_season', 'title': '推荐歌单 合集·王菲：你快乐所以我快乐'},
  {'id': '1134199', 'type': 'bili_season', 'title': '推荐歌单 合集·影视原声'},
  {'id': '1119082', 'type': 'bili_season', 'title': '推荐歌单 合集·游戏音乐'},
  {'id': '1326355', 'type': 'bili_season', 'title': '推荐歌单 合集·ED黄老板'},
  {'id': '3995253', 'type': 'bili_season', 'title': '推荐歌单 合集·《明日方舟》音乐'},
  {'id': '3994902', 'type': 'bili_season', 'title': '推荐歌单 合集·《原神》音乐'},
  {'id': '3999786', 'type': 'bili_season', 'title': '推荐歌单 合集·《绝区零》音乐'},
  {'id': '1096252', 'type': 'bili_season', 'title': '推荐歌单 合集·私人专享'},
  {'id': '3693597', 'type': 'bili_season', 'title': '推荐歌单 合集·《黑神话：悟空》合集'},
  {'id': '1983976', 'type': 'bili_season', 'title': '推荐歌单 合集·无与伦比'},
  {'id': '3995356', 'type': 'bili_season', 'title': '推荐歌单 合集·《英雄联盟》音乐'},
  {'id': '3999771', 'type': 'bili_season', 'title': '推荐歌单 合集·主机游戏 音乐'},
  {'id': '1785860', 'type': 'bili_season', 'title': '推荐歌单 合集·演唱会实录'},
  {'id': '1227331', 'type': 'bili_season', 'title': '推荐歌单 合集·体育专区'},
  {'id': '2219179', 'type': 'bili_season', 'title': '推荐歌单 合集·解压必备'},
  {'id': '1578577', 'type': 'bili_season', 'title': '推荐歌单 合集·上海交响乐团'},
  {'id': '1612755', 'type': 'bili_season', 'title': '推荐歌单 合集·经典游曲'},
  {'id': '1740963', 'type': 'bili_season', 'title': '推荐歌单 合集·经典漫曲'},
  {'id': '1519400', 'type': 'bili_season', 'title': '推荐歌单 合集·高达'},
  {'id': '120812', 'type': 'bili_season', 'title': '推荐歌单 合集·千禧年之前的经典金曲'},
  {'id': '3866786', 'type': 'bili_season', 'title': '推荐歌单 合集·Live (2024 From Zero 世界巡演) - 林肯公园'},
  {'id': '4796717', 'type': 'bili_season', 'title': '推荐歌单 合集·纵贯线'},
  {'id': '1406317', 'type': 'bili_season', 'title': '推荐歌单 合集·周杰伦'},
  {'id': '4355599', 'type': 'bili_season', 'title': '推荐歌单 合集·林俊杰'},
  {'id': '1406323', 'type': 'bili_season', 'title': '推荐歌单 合集·陈奕迅'},
  {'id': '4220383', 'type': 'bili_season', 'title': '推荐歌单 合集·日语现场'},
  {'id': '3635260', 'type': 'bili_season', 'title': '推荐歌单 合集·陶喆'},
  {'id': '1406328', 'type': 'bili_season', 'title': '推荐歌单 合集·许嵩'},
  {'id': '3162072', 'type': 'bili_season', 'title': '推荐歌单 合集·阿黛尔'},
  {'id': '1477795', 'type': 'bili_season', 'title': '推荐歌单 合集·迈克尔·杰克逊'},
  {'id': '1406333', 'type': 'bili_season', 'title': '推荐歌单 合集·酷玩'},
  {'id': '2192336', 'type': 'bili_season', 'title': '推荐歌单 合集·春节'},
  {'id': '1635413', 'type': 'bili_season', 'title': '推荐歌单 合集·伍佰'},
  {'id': '1406311', 'type': 'bili_season', 'title': '推荐歌单 合集·歌神张学友'},
  {'id': '1911901', 'type': 'bili_season', 'title': '推荐歌单 合集·配乐集'},
  {'id': '1867441', 'type': 'bili_season', 'title': '推荐歌单 合集·张宇'},
  {'id': '1892749', 'type': 'bili_season', 'title': '推荐歌单 合集·李克勤'},
  {'id': '1704616', 'type': 'bili_season', 'title': '推荐歌单 合集·泰勒'},
  {'id': '1704623', 'type': 'bili_season', 'title': '推荐歌单 合集·艾薇儿'},
  {'id': '1635426', 'type': 'bili_season', 'title': '推荐歌单 合集·赵雷'},
  {'id': '417471', 'type': 'bili_season', 'title': '推荐歌单 合集·艺人合作'},
  {'id': '13325', 'type': 'bili_season', 'title': '推荐歌单 合集·1989 World Tour'},
  {'id': '1969319', 'type': 'bili_season', 'title': '推荐歌单 合集·Ayase-YOASOBI·MV'},
  {'id': '2006067', 'type': 'bili_season', 'title': '推荐歌单 合集·Ayase-YOASOBI·LIVE'},
  {'id': '189745', 'type': 'bili_season', 'title': '推荐歌单 合集·净慈寺合集'},
  {'id': '71510', 'type': 'bili_season', 'title': '推荐歌单 合集·雨声合集'},
  {'id': '1363249', 'type': 'bili_season', 'title': '推荐歌单 合集·番茄学习'},
  {'id': '1418248', 'type': 'bili_season', 'title': '推荐歌单 合集·【白噪音】读书丨自习丨睡眠丨冥想'},
  {'id': '3568322', 'type': 'bili_season', 'title': '推荐歌单 合集·助眠音乐'},
  {'id': '3896257', 'type': 'bili_season', 'title': '推荐歌单 合集·氛围音乐'},
  {'id': '3567922', 'type': 'bili_season', 'title': '推荐歌单 合集·氛围音乐'},
  {'id': '2047602', 'type': 'bili_season', 'title': '推荐歌单 合集·羊村助眠'},
  {'id': '3673882', 'type': 'bili_season', 'title': '推荐歌单 合集·萌宅物语'},
  {'id': '2047095', 'type': 'bili_season', 'title': '推荐歌单 合集·自然环境助眠'},
  {'id': '2083437', 'type': 'bili_season', 'title': '推荐歌单 合集·猫和老鼠'},
  {'id': '2053004', 'type': 'bili_season', 'title': '推荐歌单 合集·光遇Sky'},
  {'id': '1156187', 'type': 'bili_season', 'title': '推荐歌单 合集·失眠救星系列'},
  {'id': '747587', 'type': 'bili_season', 'title': '推荐歌单 合集·咖啡馆与爵士钢琴乐'},
  {'id': '753880', 'type': 'bili_season', 'title': '推荐歌单 合集·静静听雨'},
  {'id': '742166', 'type': 'bili_season', 'title': '推荐歌单 合集·蜗居爵士乐'},
  {'id': '745477', 'type': 'bili_season', 'title': '推荐歌单 合集·千与千寻系列'},
  {'id': '4803179', 'type': 'bili_season', 'title': '推荐歌单 合集·森林雷雨'},
  {'id': '4803612', 'type': 'bili_season', 'title': '推荐歌单 合集·城市暴雨'},
  {'id': '4803555', 'type': 'bili_season', 'title': '推荐歌单 合集·江南烟雨'},
  {'id': '243526', 'type': 'bili_season', 'title': '推荐歌单 合集·【千禧年电台】1990年至2015年氛围白噪音【二〇〇〇年过去了，我很怀念它】'},
  {'id': '1293012', 'type': 'bili_season', 'title': '推荐歌单 合集·【四季电台】白日梦想家_工作_学习_助眠_与世隔绝'},
  {'id': '2085272', 'type': 'bili_season', 'title': '推荐歌单 合集·【爵士电台】唯有爵士乐不可辜负_工作_学习_助眠_与世隔绝'},
  {'id': '243543', 'type': 'bili_season', 'title': '推荐歌单 合集·【末日电台】地球上最后一个人_避难所/战争/超现实/游戏白噪音'},
  {'id': '243552', 'type': 'bili_season', 'title': '推荐歌单 合集·【昭和电台】东京夜未眠_工作_学习_助眠_与世隔绝'},
  {'id': '3588091', 'type': 'bili_season', 'title': '推荐歌单 合集·奇异人生Life is Strange 专注陪伴音乐'},
  {'id': '2332063', 'type': 'bili_season', 'title': '推荐歌单 合集·《冥想催眠》系列-来自宇宙的声音牵引灵魂走向宁静的深处'},
  {'id': '2468426', 'type': 'bili_season', 'title': '推荐歌单 合集·《Cozy Ambient Jazz》系列——阅读、放松、发呆、做家务的音乐伴侣'},
  {'id': '2331536', 'type': 'bili_season', 'title': '推荐歌单 合集·《寺院诵唱》系列-伴随着木鱼声颂钵声纯粹本真吟诵佛经'},
  {'id': '3842790', 'type': 'bili_season', 'title': '推荐歌单 合集·复古格调·城市漫步'},
  {'id': '2318216', 'type': 'bili_season', 'title': '推荐歌单 合集·《佛教音乐》系列-经文与音乐构筑的佛音启迪'},
  {'id': '2279134', 'type': 'bili_season', 'title': '推荐歌单 合集·《艺术共鸣》系列-融合世界名画与疗愈音乐'},
  {'id': '2389253', 'type': 'bili_season', 'title': '推荐歌单 合集·《星际穿越》系列-跟随音乐和画面穿越时空星际，受撼于赛博末世，一起放空沉浸'},
  {'id': '2340196', 'type': 'bili_season', 'title': '推荐歌单 合集·《迷失虚妄》系列-跟随Lofi音乐的鼓点和节拍摇摆躯体和灵魂'},
  {'id': '2448672', 'type': 'bili_season', 'title': '推荐歌单 合集·佛歌曲'},
  {'id': '1499661', 'type': 'bili_season', 'title': '推荐歌单 合集·醉美禅音'},
  {'id': '4539173', 'type': 'bili_season', 'title': '推荐歌单 合集·大悲咒'},
  {'id': '4524020', 'type': 'bili_season', 'title': '推荐歌单 合集·贝多芬交响曲全集'},
  {'id': '4458095', 'type': 'bili_season', 'title': '推荐歌单 合集·2025年维也纳新年音乐会'},
  {'id': '4211719', 'type': 'bili_season', 'title': '推荐歌单 合集·齐默尔曼'},
  {'id': '4190729', 'type': 'bili_season', 'title': '推荐歌单 合集·[中字]【海顿】创世记'},
  {'id': '3917499', 'type': 'bili_season', 'title': '推荐歌单 合集·德沃夏克第九交响曲 卡拉扬维也纳爱乐乐团'},
  {'id': '3820666', 'type': 'bili_season', 'title': '推荐歌单 合集·三大男高音（帕瓦罗蒂 多明戈 卡雷拉斯）'},
  {'id': '3789112', 'type': 'bili_season', 'title': '推荐歌单 合集·【普契尼歌剧】图兰朵 紫禁城版'},
  {'id': '3784103', 'type': 'bili_season', 'title': '推荐歌单 合集·普契尼歌剧【图兰朵】'},
  {'id': '3764922', 'type': 'bili_season', 'title': '推荐歌单 合集·柏林森林音乐会'},
  {'id': '3764881', 'type': 'bili_season', 'title': '推荐歌单 合集·柴可夫斯基《叶甫盖尼·奥涅金》'},
  {'id': '3397644', 'type': 'bili_season', 'title': '推荐歌单 合集·贝多芬交响曲和序曲'},
  {'id': '3359859', 'type': 'bili_season', 'title': '推荐歌单 合集·德沃夏克第九交响曲'},
  {'id': '3253566', 'type': 'bili_season', 'title': '推荐歌单 合集·施特劳斯·拉德斯基进行曲'},
  {'id': '3206291', 'type': 'bili_season', 'title': '推荐歌单 合集·欧美音乐现场'},
  {'id': '431918', 'type': 'bili_season', 'title': '推荐歌单 合集·贝多芬'},
  {'id': '876659', 'type': 'bili_season', 'title': '推荐歌单 合集·穿越星际'},
  {'id': '436932', 'type': 'bili_season', 'title': '推荐歌单 合集·莫扎特'},
  {'id': '444191', 'type': 'bili_season', 'title': '推荐歌单 合集·海顿'},
  {'id': '431910', 'type': 'bili_season', 'title': '推荐歌单 合集·马勒'},
  {'id': '431887', 'type': 'bili_season', 'title': '推荐歌单 合集·卡拉扬'},
  {'id': '431910', 'type': 'bili_season', 'title': '推荐歌单 合集·马勒'},
  {'id': '436887', 'type': 'bili_season', 'title': '推荐歌单 合集·柴可夫斯基'},
  {'id': '436915', 'type': 'bili_season', 'title': '推荐歌单 合集·巴赫'},
  {'id': '436989', 'type': 'bili_season', 'title': '推荐歌单 合集·小提琴 | 大提琴 | 钢琴 | 美声 | 交响乐 | 古典音乐'},
  {'id': '3629748', 'type': 'bili_season', 'title': '推荐歌单 合集·AI修复郭德纲相声'},
  {'id': '3644679', 'type': 'bili_season', 'title': '推荐歌单 合集·AI修复郭德纲单口相声'},
  {'id': '3629182', 'type': 'bili_season', 'title': '推荐歌单 合集·郭德纲无唱助眠相声'},
  {'id': '1302800', 'type': 'bili_season', 'title': '推荐歌单 合集·每天漫步雨雪'},
  {'id': '4553891', 'type': 'bili_season', 'title': '推荐歌单 合集·马三立相声集'},
  {'id': '4262997', 'type': 'bili_season', 'title': '推荐歌单 合集·刘宝瑞高清修复助眠相声'},
  {'id': '3329955', 'type': 'bili_season', 'title': '推荐歌单 合集·侯宝林相声高清修复'},
  {'id': '2940848', 'type': 'bili_season', 'title': '推荐歌单 合集·赵本山'},
  {'id': '3484556', 'type': 'bili_season', 'title': '推荐歌单 合集·回忆春节'},
  {'id': '2947903', 'type': 'bili_season', 'title': '推荐歌单 合集·侯耀文'},
  {'id': '182147', 'type': 'bili_season', 'title': '推荐歌单 合集·4K春晚 戏曲'},
  {'id': '2948951', 'type': 'bili_season', 'title': '推荐歌单 合集·相声'},
  {'id': '2940903', 'type': 'bili_season', 'title': '推荐歌单 合集·冯巩'},
  {'id': '103727', 'type': 'bili_season', 'title': '推荐歌单 合集·水浒传 修复版'},
  {'id': '35431', 'type': 'bili_season', 'title': '推荐歌单 合集·4k修复 西游记'},
  {'id': '2947877', 'type': 'bili_season', 'title': '推荐歌单 合集·马季'},
  {'id': '2940957', 'type': 'bili_season', 'title': '推荐歌单 合集·陈佩斯'},
  {'id': '189166', 'type': 'bili_season', 'title': '推荐歌单 合集·Beyond 黄家驹、黄贯中、黄家强、叶世荣'},
  {'id': '2947924', 'type': 'bili_season', 'title': '推荐歌单 合集·姜昆'},
  {'id': '114764', 'type': 'bili_season', 'title': '推荐歌单 合集·张学友（Jacky Cheung）'},
  {'id': '1374170', 'type': 'bili_season', 'title': '推荐歌单 合集·古典音乐'},
  {'id': '1373124', 'type': 'bili_season', 'title': '推荐歌单 合集·楼上噪音解决'},
  {'id': '1888349', 'type': 'bili_season', 'title': '推荐歌单 合集·摇滚音乐'},
  {'id': '1566078', 'type': 'bili_season', 'title': '推荐歌单 合集·爵士音乐'},
  {'id': '1763356', 'type': 'bili_season', 'title': '推荐歌单 合集·蔡琴'},
  {'id': '1436167', 'type': 'bili_season', 'title': '推荐歌单 合集·人声hifi'},
  {'id': '41', 'type': 'bili_season', 'title': '推荐歌单 合集·BILLBOARD 美国单曲榜'},
  {'id': '9680', 'type': 'bili_season', 'title': '推荐歌单 合集·每周歌曲推荐'},
  {'id': '266', 'type': 'bili_season', 'title': '推荐歌单 合集·Official Chart 英国单曲榜'},
  {'id': '443', 'type': 'bili_season', 'title': '推荐歌单 合集·BILLBOARD 全球单曲榜'},
  {'id': '4256191', 'type': 'bili_season', 'title': '推荐歌单 合集·Thai Playlist'},
  {'id': '48627', 'type': 'bili_season', 'title': '推荐歌单 合集·历年华语乐坛经典回顾'},
  {'id': '2122597', 'type': 'bili_season', 'title': '推荐歌单 合集·2023年各月份热歌排行榜'},
  {'id': '4142178', 'type': 'bili_season', 'title': '推荐歌单 合集·【Playlist】音乐合集'},
  {'id': '1784187', 'type': 'bili_season', 'title': '推荐歌单 合集·LOFI环境系列'},
  {'id': '1828749', 'type': 'bili_season', 'title': '推荐歌单 合集·LOFI街景'},
  {'id': '1975341', 'type': 'bili_season', 'title': '推荐歌单 合集·像素Lofi'},
  {'id': '2372215', 'type': 'bili_season', 'title': '推荐歌单 合集·漫步LOFI'},
  {'id': '2074929', 'type': 'bili_season', 'title': '推荐歌单 合集·【一人学习LOFI合集】'},
  {'id': '2787260', 'type': 'bili_season', 'title': '推荐歌单 合集·狐狸与少女'},
  {'id': '1647617', 'type': 'bili_season', 'title': '推荐歌单 合集·LOFI敲代码系列'},
  {'id': '1817781', 'type': 'bili_season', 'title': '推荐歌单 合集·ET LOFI studio'},
  {'id': '4720896', 'type': 'bili_season', 'title': '推荐歌单 合集·【轻音乐歌单】| 学习 放松 治愈'},
  {'id': '4092430', 'type': 'bili_season', 'title': '推荐歌单 合集·【Playlist歌单】| 私藏宝藏歌单'},
  {'id': '2877786', 'type': 'bili_season', 'title': '推荐歌单 合集·五音療疾'},
  {'id': '1680358', 'type': 'bili_season', 'title': '推荐歌单 合集·疗愈舒缓'},
  {'id': '4511241', 'type': 'bili_season', 'title': '推荐歌单 合集·专辑'},
  {'id': '4652973', 'type': 'bili_season', 'title': '推荐歌单 合集·循环'},
  {'id': '4652954', 'type': 'bili_season', 'title': '推荐歌单 合集·日推'},
  {'id': '4511239', 'type': 'bili_season', 'title': '推荐歌单 合集·运动'},
  {'id': '4558738', 'type': 'bili_season', 'title': '推荐歌单 合集·乐队'},
  {'id': '1739397', 'type': 'bili_season', 'title': '推荐歌单 合集·中世纪|凯尔特|酒馆等风格合集'},
  {'id': '1739402', 'type': 'bili_season', 'title': '推荐歌单 合集·游戏音乐合集'},
  {'id': '2209882', 'type': 'bili_season', 'title': '推荐歌单 合集·吟游诗人合集'},
  {'id': '1755796', 'type': 'bili_season', 'title': '推荐歌单 合集·北欧维京音乐系列'},
  {'id': '1986805', 'type': 'bili_season', 'title': '推荐歌单 合集·节日音乐'},
  {'id': '1812732', 'type': 'bili_season', 'title': '推荐歌单 合集·幻想&魔法&奇幻&史诗音乐合集'},
  {'id': '1739406', 'type': 'bili_season', 'title': '推荐歌单 合集·单曲合集'},
  {'id': '4216345', 'type': 'bili_season', 'title': '推荐歌单 合集·小千代の音乐补完计划'},
  {'id': '1855821', 'type': 'bili_season', 'title': '推荐歌单 合集·进击的巨人音乐盘点合集'},
  {'id': '32658', 'type': 'bili_season', 'title': '推荐歌单 合集·凯哥学英语'},
  {'id': '2836893', 'type': 'bili_season', 'title': '推荐歌单 合集·久石让曲目精选'},
  {'id': '2798585', 'type': 'bili_season', 'title': '推荐歌单 合集·Taylor Swift-THE TORTURED POETS DEPARTMENT'},
  {'id': '1910387', 'type': 'bili_season', 'title': '推荐歌单 合集·摇滚与流行｜我们的经典，我们的摇滚'},
  {'id': '1847641', 'type': 'bili_season', 'title': '推荐歌单 合集·1989 (Taylor\'s Version)歌词MV合集'},
  {'id': '1806326', 'type': 'bili_season', 'title': '推荐歌单 合集·【Troye Sivan】新专《Something To Give Each Other》'},
  {'id': '1380315', 'type': 'bili_season', 'title': '推荐歌单 合集·Taylor Swift泰勒·斯威夫特官方MV精选'},
  {'id': '1973224', 'type': 'bili_season', 'title': '推荐歌单 合集·Taylor Swift "The Eras Tour"时代巡回演唱会'},
  {'id': '1616825', 'type': 'bili_season', 'title': '推荐歌单 合集·嘻哈50年 | 传世经典的自由宣言'},
  {'id': '1625207', 'type': 'bili_season', 'title': '推荐歌单 合集·Beyond｜40年光辉岁月'},
  {'id': '1358751', 'type': 'bili_season', 'title': '推荐歌单 合集·环球音乐J-POP精选'},
  {'id': '2623786', 'type': 'bili_season', 'title': '推荐歌单 合集·张国荣·永远的哥哥风华绝代'},
  {'id': '1449094', 'type': 'bili_season', 'title': '推荐歌单 合集·Justin Bieber贾斯汀·比伯官方MV精选'},
  {'id': '1380269', 'type': 'bili_season', 'title': '推荐歌单 合集·陈奕迅官方现场精选'},
  {'id': '1304816', 'type': 'bili_season', 'title': '推荐歌单 合集·Avicii艾维奇的电音经典'},
  {'id': '1260237', 'type': 'bili_season', 'title': '推荐歌单 合集·日韩4K修复'},
  {'id': '1255767', 'type': 'bili_season', 'title': '推荐歌单 合集·欧美4K修复'},
  {'id': '1260240', 'type': 'bili_season', 'title': '推荐歌单 合集·华语4K修复'},
  {'id': '46418', 'type': 'bili_season', 'title': '推荐歌单 合集·【4K修复】Nightwish夜愿乐队2005时代终结演唱会'},
  {'id': '103735', 'type': 'bili_season', 'title': '推荐歌单 合集·【4K修复】枪炮与玫瑰1992东京演唱会'},
  {'id': '215809', 'type': 'bili_season', 'title': '推荐歌单 合集·【霉霉】泰勒·斯威夫特音乐合集'},
  {'id': '8008', 'type': 'bili_season', 'title': '推荐歌单 合集·【4K修复】Nightwish夜愿乐队Wacken 2013演唱会'},
  {'id': '1003508', 'type': 'bili_season', 'title': '推荐歌单 合集·日本歌手合集：中岛美雪、滨崎步、美依礼芽、米津玄师、仓木麻衣、坂井泉水、Wands'},
  {'id': '1282981', 'type': 'bili_season', 'title': '推荐歌单 合集·那些经典的动漫歌曲'},
  {'id': '2069904', 'type': 'bili_season', 'title': '推荐歌单 合集·ost歌曲合集'},
  {'id': '4704429', 'type': 'bili_season', 'title': '推荐歌单 合集·唐宋摇滚'},
  {'id': '1707990', 'type': 'bili_season', 'title': '推荐歌单 合集·『GUNDAM MUSIC』'},
  {'id': '2852940', 'type': 'bili_season', 'title': '推荐歌单 合集·『MUSIC LIVE』'},
  {'id': '3095846', 'type': 'bili_season', 'title': '推荐歌单 合集·『影视原声音乐』'},
  {'id': '4445811', 'type': 'bili_season', 'title': '推荐歌单 合集·TOKYO ASMR MASSAGE 合集'},
  {'id': '2966', 'type': 'bili_season', 'title': '推荐歌单 合集·迈克尔·杰克逊超清合集'},
  {'id': '510637', 'type': 'bili_season', 'title': '推荐歌单 合集·后街男孩超清合集'},
  {'id': '3278', 'type': 'bili_season', 'title': '推荐歌单 合集·皇后乐队超清合集'},
    {'id': '513550', 'type': 'bili_season', 'title': '推荐歌单 合集·小甜甜布兰妮超清视频'},
  {'id': '4201012', 'type': 'bili_season', 'title': '推荐歌单 合集·梶浦由记'},
    {'id': '3654466', 'type': 'bili_season', 'title': '推荐歌单 合集·动画MV'},
    {'id': '3403831', 'type': 'bili_season', 'title': '推荐歌单 合集·高达'},
  {'id': '1097290', 'type': 'bili_season', 'title': '推荐歌单 合集·Whiskey | Jazz | Blues'},
    {'id': '4772899', 'type': 'bili_season', 'title': '推荐歌单 合集·Jazzy x Lofi 自习岛 | 学习 工作 放松 氛围'},
    {'id': '1109355', 'type': 'bili_season', 'title': '推荐歌单 合集·City-Pop° | 城市流行'},
  {'id': '1369602', 'type': 'bili_season', 'title': '推荐歌单 合集·FUNK MEGA MIX | 放克风格| G-funk | 放克爵士 | 放克摇滚 | 电子放克'},
    {'id': '4904693', 'type': 'bili_season', 'title': '推荐歌单 合集·「收藏向」全球顶流音乐歌手合集'},
    {'id': '1213636', 'type': 'bili_season', 'title': '推荐歌单 合集·Classical | 古典音乐'},
  {'id': '1208544', 'type': 'bili_season', 'title': '推荐歌单 合集·Film | 经典电影原声带 | 配乐 | 插曲 | 歌曲'},
  {'id': '1124528', 'type': 'bili_season', 'title': '推荐歌单 合集·Baroque | 【艺术瑰宝】巴洛克音乐，古典音乐的黄金时代'},
  {'id': '1109249', 'type': 'bili_season', 'title': '推荐歌单 合集·Anime BGM | OST Collection Full | 经典动漫音乐歌曲合集'},
  {'id': '1264953', 'type': 'bili_season', 'title': '推荐歌单 合集·Sweet Dreams ＳＬＥＥＰＹ  | Lofi hip hop睡眠 学习 放松'},
  {'id': '1102076', 'type': 'bili_season', 'title': '推荐歌单 合集·Chill-hop | 低保真 | Lo-Fi Hip Hop | Jazz复古 氛围'},
  {'id': '1097605', 'type': 'bili_season', 'title': '推荐歌单 合集·泽野弘之 | Sawano Hiroyuki 动漫原声合集［nZk］'},
  {'id': '1264819', 'type': 'bili_season', 'title': '推荐歌单 合集·【幻想乡的邀请】东方Project 探索幻想乡的秘密'},
  {'id': '1218878', 'type': 'bili_season', 'title': '推荐歌单 合集·Driving Music | 驾驶音乐'},
  {'id': '1517778', 'type': 'bili_season', 'title': '推荐歌单 合集·「百大电音DJ」各类风格电音MIX 抖腿节奏向★玩游戏必备电音BUFF✈『NIGHT CLUB』'},
  {'id': '1367257', 'type': 'bili_season', 'title': '推荐歌单 合集·Country Music | 美国乡村音乐 | 民谣 | 牛仔音乐 | 西部摇摆乐'},
  {'id': '1170820', 'type': 'bili_season', 'title': '推荐歌单 合集·Opera | 歌剧合集 | 不定期更新'},
  {'id': '1111544', 'type': 'bili_season', 'title': '推荐歌单 合集·史诗战斗音乐 | 管弦Epic Mix'},
  {'id': '1124561', 'type': 'bili_season', 'title': '推荐歌单 合集·Impressionist | 印象音乐'},
  {'id': '', 'type': 'bili_season', 'title': '推荐歌单 '},
  {'id': '', 'type': 'bili_season', 'title': '推荐歌单 '},
  {'id': '', 'type': 'bili_season', 'title': '推荐歌单 '},
  {'id': '', 'type': 'bili_season', 'title': '推荐歌单 '},
  {'id': '', 'type': 'bili_season', 'title': '推荐歌单 '},

];